global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator-distant'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['192.168.56.7:8082']

  - job_name: 'jenkins'
    metrics_path: '/prometheus'
    static_configs:
      - targets: ['192.168.5.7:8080']

  - job_name: 'nginx-exporter'
    metrics_path: /metrics
    static_configs:
      - targets: ['192.168.56.7:9113']

